import React from "react";
import { AlertTriangle, ShieldCheck } from "lucide-react";

export const SafetyNotice: React.FC = () => {
  return (
    <div className="p-8 bg-amber-50 rounded-[2.5rem] border-2 border-amber-200/50 shadow-xl shadow-amber-900/5 animate-in fade-in slide-in-from-top-4 duration-1000">
      <div className="flex items-center gap-4 mb-4">
        <div className="w-12 h-12 bg-amber-500 rounded-2xl flex items-center justify-center shadow-lg">
          <AlertTriangle className="text-white w-6 h-6" />
        </div>
        <div>
          <h4 className="text-lg font-black text-amber-900 italic uppercase italic">Safety Protocol Active</h4>
          <p className="text-[10px] font-black uppercase tracking-widest text-amber-600 mt-1">Institutional Guardrails v1.0</p>
        </div>
      </div>
      <p className="text-xs font-bold text-amber-800 leading-relaxed italic opacity-80">
        ⚠️ This advice is generated by a multi-source AI model using market and weather telemetry. 
        It is provided for informational purposes only. Please verify critical financial or agricultural 
        decisions with local government experts or bank officials before execution.
      </p>
      <div className="mt-4 flex items-center gap-2 text-emerald-700 bg-white/40 px-4 py-2 rounded-full inline-flex">
        <ShieldCheck className="w-4 h-4" />
        <span className="text-[9px] font-black uppercase tracking-widest">Decision Integrity Verified</span>
      </div>
    </div>
  );
};
